Added winner logic to TTT.
jenriquecerda/elixirTTT pull request #4
Opened 2019-09-10 19:42 UTC by jenriquecerda

TTT checks if there is a winner and if so, ends game.
Winning logic was added inside winner_logic module, which checks for winners according to the combinations provided.

2019-09-10 20:59 UTC, jassa commented on README.md
> +
Con "```" puedes crear sintaxis de código, ej:

<img width="190" alt="Screen Shot 2019-09-10 at 3 39 28 PM" src="https://user-images.githubusercontent.com/368802/64648757-3150ec00-d3e1-11e9-9133-7c028048b6ec.png">

igual a:

## Installation

```
mix escripts.build
```

2019-09-10 20:59 UTC, jassa commented on lib/game/tictactoe.ex
>      else
parece que tienes una razón de cambio dividida:
```
Board.is_full?(board)
WinnerLogic.is_winner?(result)
```

también es un poco confuso el nombre de la var "result" para referirte al board

2019-09-10 20:59 UTC, jassa commented on test/winner_logic/winner_logic_test.exs
> +    assert WinnerLogic.is_winner?(board) == true
puedes omitir == true

2019-09-10 20:59 UTC, jassa commented on test/winner_logic/winner_logic_test.exs
> +  end
cada prueba es valiosa pero hay mucha duplicación, cómo puedes evitarla?

2019-09-10 20:59 UTC, jassa commented on test/game/tictactoe_test.exs
> +    assert TicTacToe.play_game(board, players) == winner_board
board, winner_board, y los dos players @ + todos los "@" causan un poco de ruido

parecen haber más elementos de los necesarios para esta prueba

los elementos esenciales que veo son:
- 1 board casi completo (ej 1 = x, 2 = x)
- 1 player que juegue el movimiento faltante (3 = x)
- una comparación como que play_game(board, [player]) te regrese un board con 1,2,3=x y el resto vacío

pueden ser 2 jugadores también pero los "@" son un poco confusos

2019-09-11 14:17 UTC, jenriquecerda commented on test/winner_logic/winner_logic_test.exs
> +  end
Tienes razon. Listo.

2019-09-11 14:29 UTC, jenriquecerda commented on test/game/tictactoe_test.exs
> +    assert TicTacToe.play_game(board, players) == winner_board
Creo que quedo mejor...

2019-09-11 16:18 UTC, XeryuzRouge commented on test/winner_logic/winner_logic_test.exs
> +        assert WinnerLogic.is_winner?(board)
El código parece estar bien, solo voy a remarcar algunas consideraciones para la comunicación por medio de los nombres para futuras funciones, clases, etc.

Viendo este assert por primera vez, no me queda muy claro entender que es lo que sucede en esta función. En otras palabras:
A `.is_winner?` se le esta pasando `board` como parametro, pero "is_winner?" suena a que le voy a pasar un jugador para que me diga si es ganador o no (recuerdo lo que me dijiste de la guía de estilos, pero tal vez puedas seguir esta misma y comunicar mejor lo que hace esta función).
Posibles problemas con nombres como `WinnerLogic`son:

-El hecho de que, palabras como "Logic" nos da más libertad de darle la **responsabilidad** que queramos, en 
  lugar de usar conceptos más concretos y fáciles de encapsular como 'Board', 'Player' o 'Match'.

-(Probablemente lo siguiente ya lo haz leído en alguna parte (No estoy seguro si esto también aplica en 
  programación funcional)): En programación orientada a objetos, las clases se les ve como "objetos" (duh), por lo 
  que se les trata de dar un nombre de 'algo': 'Board', 'Winner', 'Score', esto para que las funciones a su vez sean 
  una acción que realiza este 'algo': 'Board.empty', 'Board.empty?', 'Winner.set("X")', 'Score.current'.

Siguiendo estas ideas, tal vez podrías pensar en `WinnerLogic` como una 'persona' con **la tarea** de estar verificando si ya hay un ganador en el juego. Que nombre le pondrías a alguien encargado de esa única tarea?

2019-09-11 16:49 UTC, jenriquecerda commented on test/winner_logic/winner_logic_test.exs
> +        assert WinnerLogic.is_winner?(board)
Voy a cambiarlo a "has_winner?" para pasarle un board y me diga si si tiene winner...

2019-09-17 16:55 UTC, jassa requested changes

2019-09-17 16:55 UTC, jassa commented on lib/game/tictactoe.ex
> +        IO.puts(current_player.device, "#{current_player.symbol} wins!")
Smell: detalles. Antes hablabas de current players que jugaban, ahora tictactoe.ex sabe que current player tiene un device (forzando a todos los players a tener "device").

Relacionado al smell: qué pasa si es H vs C y gana/current player es C?

2019-09-17 16:55 UTC, jassa commented on test/WinningRules/winning_rules_test.exs
> +    end
los lenguajes funcionales típicamente tienen herramientas más concisas para procesar colecciones, ej: map, reduce, ...

2019-09-17 16:55 UTC, jassa commented on test/game/tictactoe_test.exs
> +  end
👍 por la FakeWinningLogic
de esta manera al game loop no le importa específicamente cómo gana, simplemente qué pasa cuando gana (sigue SOliD)

2019-09-17 16:55 UTC, jassa commented on test/game/tictactoe_test.exs
> +  end
repetición:
```
if (true/false) do
  true
else
  false
end
```

2019-09-17 16:55 UTC, jassa commented on test/game/tictactoe_test.exs
> +    fake_player = Player.new("@", &fake_winner/2, @fake_input)
por qué no usar un signo más típico? (X/O)
para evitar confusión con si es un player, o el "@" tendrá un significado especial

2019-09-17 18:16 UTC, jenriquecerda commented on lib/game/tictactoe.ex
> +        IO.puts(current_player.device, "#{current_player.symbol} wins!")
Lo puse dentro de Player, es un detalle propio pero ahora creo que Player tiene dos responsabilidades, crear su propia estructura e imprimir que gano...

2019-09-17 18:17 UTC, jenriquecerda commented on test/game/tictactoe_test.exs
> +    fake_player = Player.new("@", &fake_winner/2, @fake_input)
solo era como para ensenar que se puede de todo... lo cambio.

2019-09-17 21:54 UTC, jassa commented on lib/game/tictactoe.ex
> +      else
si empezamos por las pruebas, me imagino algo como:

```
it "game is over when there is a winner" do  
  game = TicTacToe.play_game(board, players, FakeRules)
  assert game.is_over?
  assert game.winner == "X"
end

defmodule FakeRules
  def winner(board) do
    "X"
  end

  def has_winner?(board) do
    true
  end
end
```

y me pregunto cómo anunciar el winner, parece que puede ser el resultado de play_game (según mi tren mental de TDD)

2019-09-17 21:54 UTC, jassa commented on test/game/tictactoe_test.exs
> +    assert TicTacToe.play_game(board, players, FakeLogic) == winner_board
puedes agregar esta misma prueba pero para un player que no tiene `is_winner` como CPU? como está el código ahora parece que hay una dependencia de que el player ganador tenga is_winner, y no todos los players lo tienen. Aclaro, creo que es correcto que no requieran `is_winner`, CPU no haría nada, sin embargo si CPU pasa por ese flujo el programa tronaría

2019-09-18 15:23 UTC, jenriquecerda commented on lib/game/tictactoe.ex
> +      else
Pero no seria agregarle una responsabilidad mas al loop? Saber el quien gano. Siento, por las pruebas que la responsabilidad del tictactoe es proveer de un "loop" para alternar jugadores y que el tablero sea llenado. Esa responsabilidad ya esta en Player...

2019-09-19 18:20 UTC, jassa commented on test/game/tictactoe_test.exs
> +          end
por qué FakeInput y no FakeOutput o FakeIO?

2019-09-19 18:20 UTC, jassa commented on test/game/tictactoe_test.exs
> +  end
:+1:

2019-09-19 18:20 UTC, jassa commented on test/game/tictactoe_test.exs
> +end
`printed_message` suena ambiguo, pueden imprimirse muchos msgs durante un juego de TTT

2019-09-19 18:23 UTC, jenriquecerda commented on test/game/tictactoe_test.exs
> +          end
Si, ya lo cambie. Me fui con la finta de como se usaba pero en realidad recibe y envia. Tienes razon.

2019-09-19 18:28 UTC, jassa commented on lib/game/tictactoe.ex
> +      IO.puts(output, "Player #{winning_rules.winner(board)} wins")
qué pasa si no hay winner?

2019-09-19 18:31 UTC, jenriquecerda commented on test/game/tictactoe_test.exs
> +end
si, tmb pense en eso mismo pero si crei q la funcion debia llamarse asi porq eso es lo q hace, recupera mensajes. tal vez voy a asignar una variable...

2019-09-19 20:54 UTC, jenriquecerda commented on lib/game/tictactoe.ex
> +      IO.puts(output, "Player #{winning_rules.winner(board)} wins")
Listo. Si lo consideraba mi WinningRules pero no estaba implementado en TicTacToe.

2019-09-19 21:08 UTC, jassa approved these changes

2019-09-19 21:21 UTC, merged